language: node_js
node_js:
  - "node"
require: sudo
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libkrb5-dev
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/32d1f66038909312d4ae
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
